### ISSUE TITLE
TypeError: a bytes-like object is required, not 'NoneType'

### ISSUE THREAD

**Issue by ringsIdea** [ChenhongyiYang/GPViT#4]
When I run  following instruction:
bash tools/dist_test.sh configs/gpvit/gpvit_l1.py gpvit_l1_in1k_300e.pth  1 --metrics accuracy

The Error occurs as following:
 File "tools/test.py", line 243, in <module>
    main()
  File "tools/test.py", line 200, in main
    args.gpu_collect)
  File "/opt/data/private/hnz/GPViT-main/mmcls/apis/test.py", line 118, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/data/private/hnz/GPViT-main/mmcls/datasets/base_dataset.py", line 97, in __getitem__
    return self.prepare_data(idx)
  File "/opt/data/private/hnz/GPViT-main/mmcls/datasets/base_dataset.py", line 91, in prepare_data
    return self.pipeline(results)
  File "/opt/data/private/hnz/GPViT-main/mmcls/datasets/pipelines/compose.py", line 33, in __call__
    data = t(data)
  File "/opt/data/private/hnz/GPViT-main/mmcls/datasets/pipelines/loading.py", line 116, in __call__
    img = mmcv.imfrombytes(img_bytes, flag=self.color_type)
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/mmcv/image/io.py", line 257, in imfrombytes
    img_np = np.frombuffer(content, np.uint8)
TypeError: a bytes-like object is required, not 'NoneType'

Traceback (most recent call last):
  File "/root/miniconda3/envs/vision/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/vision/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/root/miniconda3/envs/vision/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/vision/bin/python', '-u', 'tools/test.py', '--local_rank=0', 'configs/gpvit/gpvit_l1.py', 'gpvit_l1_in1k_300e.pth', '--launcher', 'pytorch', '--metrics', 'accuracy']' returned non-zero exit status 1.

Somebody know why?

**Comment by ChenhongyiYang** [comment]
Hi,

Thank you for trying our repo :-) 

I think the problem is caused by incorrect dataset placement.
